version: '3.9'

volumes:
  grafana_data: {}
  prometheus_data: {}

services:
  storage_api:
    build: ./src
    ports:
      - "5000:5000"
      - "8000:8000"
    environment:
      FLASK_APP: ./src/storage/_init__.py
      FLASK_ENV: production
    command: gunicorn --workers=4 --bind=0.0.0.0:5000 storage:app
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./deploy/prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./deploy/grafana/provisioning/:/etc/grafana/provisioning/
    depends_on:
      - prometheus