apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |-
    global:
      scrape_interval: 30s
      evaluation_interval: 30s
    scrape_configs:
      - job_name: "storage_api"
        scrape_interval: 10s
        static_configs:
          - targets: ["storage-api-svc:80"]
