apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-api
  labels:
    app: storage-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage-api
  template:
    metadata:
      labels:
        app: storage-api
    spec:
      containers:
      - name: storage-api
        image: storage-api:latest
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
      volumes:
      - name: data-volume
        hostPath:
          path: /app/storage-api
